{{- if .Values.traefik.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: silverbullet
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.traefik.ingress.domain }}`)
      priority: 10
      services:
        - name: {{ include "silverbullet.fullname" . }}
          port: 80

  tls: {}
{{- end }}